name: Deploy web build

on:
  push:
    branches:
    - stock_jgr

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  emscripten:
    name: Emscripten

    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        cd os/emscripten
        docker build -t emsdk-lzma .
        cd ../..
        mkdir build-host
        docker run --rm -v $(pwd):$(pwd) -u $(id -u):$(id -g) --workdir $(pwd)/build-host emsdk-lzma cmake .. -DOPTION_TOOLS_ONLY=ON
        docker run --rm -v $(pwd):$(pwd) -u $(id -u):$(id -g) --workdir $(pwd)/build-host emsdk-lzma make -j$(nproc) tools
        mkdir em_build
        docker run --rm -v $(pwd):$(pwd) -u $(id -u):$(id -g) --workdir $(pwd)/em_build emsdk-lzma emcmake cmake .. -DHOST_BINARY_DIR=$(pwd)/build-host -DCMAKE_BUILD_TYPE=RelWithDebInfo -DOPTION_USE_ASSERTS=OFF
        docker run --rm -v $(pwd):$(pwd) -u $(id -u):$(id -g) --workdir $(pwd)/em_build emsdk-lzma emmake make -j$(nproc)
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: em_build # The folder the action should deploy.
        CLEAN: true # Automatically remove deleted files from the deploy branch- name: Deploy 🚀