name: Build nightly binaries

on: [push]

jobs:
  build-nightlies:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, ubuntu-16.04]
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: build
      run: cmake --build build
    - uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: |
          build/openttd
          build/lang/
          build/ai/
          build/scripts/
